#!/bin/sh
# Base file to be sourced on all machines
alias\
    ll='ls -l' \
    la='ls -al' \
    l='ls -l' \
    _date='date +%F' \
    ka="killall" \
    mkd="mkdir -pv" \
    gau="git add -u" \
    ga="git add" \
    cdc='cd ${XDG_CONFIG_HOME}'\
    e='${EDITOR}'\
    v='${EDITOR} -R'\
    vim='${EDITOR}'\
    vi='${EDITOR}'

command -v todo > /dev/null 2>&1  && alias ta="todo new" && alias te="todo edit"
